### PR TITLE
feature: support running inside swoole coroutines

### PR DESCRIPTION
**Pull request by shellphy**
| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌ 
| New feature?  | compatible swoole coroutine
| Issues        | closes: [1951](https://github.com/roadrunner-server/roadrunner/issues/1951) 
| Docs PR       | spiral/docs#... 

Associate a static seq variable with a link handle instead of an RPC static variable

### CODE REVIEW

**Comment by roxblnfk** [comment]
Looks ok.
Could you add a test with concurrent requests?

**Comment by rustatian** [comment]
@shellphy Thank you for the PR 👍 
Could you please add docs with a simple example of using as well to the github.com/roadrunner-server/docs repository?

**Comment by shellphy** [comment]
I added swoole's test case, but there are two problems that can't be tested. 

One is the exception problem, because swoole's exception handling is a little different from phpunit's, so I don't know how to test it. 

The other is the test of long raw body. The socket message length seems to be limited in the swoole environment.

However, this does not affect the use of most cases.

**Comment by rustatian** [comment]
@shellphy All CI tests are red 😉 Needs to be green 🟢

**Comment by roxblnfk** [comment]
> Could you please add docs with a simple example of using as well to the github.com/roadrunner-server/docs repository?

The change itself does not require documentation. Do you mean an example of usage with Swoole?

**Comment by rustatian** [comment]
> > Could you please add docs with a simple example of using as well to the github.com/roadrunner-server/docs repository?
> 
> The change itself does not require documentation. Do you mean an example of usage with Swoole?

> docs with a simple example of using

**Comment by shellphy** [comment]
> > Could you please add docs with a simple example of using as well to the github.com/roadrunner-server/docs repository?
> 
> The change itself does not require documentation. Do you mean an example of usage with Swoole?

The CI environment lacks the swoole extension:

Error: Class 'Swoole\Coroutine' not found

**Comment by shellphy** [comment]
> > > Could you please add docs with a simple example of using as well to the github.com/roadrunner-server/docs repository?
> > 
> > 
> > The change itself does not require documentation. Do you mean an example of usage with Swoole?
> 
> > docs with a simple example of using



> > > Could you please add docs with a simple example of using as well to the github.com/roadrunner-server/docs repository?
> > 
> > 
> > The change itself does not require documentation. Do you mean an example of usage with Swoole?
> 
> > docs with a simple example of using

roadrunner itself does not rely on swoole, and this patch I made is only compatible with swoole's coroutine environment in rpc project. I think this is not the core function of this project, and few people use swoole and roadrunner at the same time, so I don't think it is necessary to write a special document

**Comment by rustatian** [comment]
@shellphy 
> roadrunner itself does not rely on swoole, and this patch I made is only compatible with swoole's coroutine environment in rpc project. 

Certainly. You may create a separate pipeline or job and include Swoole extension in it and run the particular tests (concurrent, if you want) in it. 
Or, and this is up to you, add concurrent tests (since your core fix is about that) and remove Swoole coroutines test and `"ext-swoole": "Swoole gocoroutine support",` from your PR.

If you decide to leave Swoole, I would appreciate it if you add a simple example of using it with some brief explanation and links on how to install this extension.
If you decide to remove it, docs are not needed for sure, but you need to test concurrent requests via CI.

**Comment by rustatian** [comment]
@shellphy we discussed internally, sorry for the confusion, I appreciate what you have done. Since I am not a PHP dev, I thought that Swoole is required to properly test this functionality. Since it is not required, could you please remove this dependency from the suggest block, CI and write a regular PHP tests?

**Comment by shellphy** [comment]
> @shellphy we discussed internally, sorry for the confusion, I appreciate what you have done. Since I am not a PHP dev, I thought that Swoole is required to properly test this functionality. Since it is not required, could you please remove this dependency from the suggest block, CI and write a regular PHP tests?

OK

**Comment by msmakouz** [comment]
@shellphy Thanks!

**Pull request merged**
